on:
  workflow_dispatch:
    inputs:
      dispatch_token:
        description: 'Token that authorize the dispatch'
        required: true
      head_sha:
        description: 'Head commit SHA that dispatched the workflow'
        required: true
      pr_author_username:
        description: 'Pull Request author username'
        required: true
      pr_number:
        description: 'Pull Request number that dispatched the workflow'
        required: true

jobs:
  evaluator:
    runs-on: self-hosted
    name: Evaluator Job
    steps:
      - name: Check out project repository
        uses: actions/checkout@v2
      - name: Checkout Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout-action

      - name: Run checkout protected files
        uses: ./.github/actions/blocked-files-checkout-action
        with:
          restore_branch: 'master'
