on:
  workflow_dispatch:
    inputs:
      dispatch_token:
        description: 'Token that authorize the dispatch'
        required: false
      head_sha:
        description: 'Head commit SHA that dispatched the workflow'
        required: false
      pr_author_username:
        description: 'Pull Request author username'
        required: false
      pr_number:
        description: 'Pull Request number that dispatched the workflow'
        required: false

jobs:
  evaluator:
    runs-on: self-hosted
    name: Evaluator Job
    steps:
      - name: Check out project repository
        uses: actions/checkout@v2
