on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number that dispatched the workflow'
        required: true

jobs:
  evaluator:
    runs-on: self-hosted
    name: Evaluator Job
    steps:
      - name: Check out project repository
        uses: actions/checkout@v2
